#!/bin/bash
#PBS -P xe2
#PBS -q knl
#PBS -l walltime=48:00:00
#PBS -l mem=32GB
#PBS -l jobfs=32GB
#PBS -l ncpus=64
#PBS -l other=hyperthread

## The job will be executed from current working directory instead of home.
#PBS -l wd

#PBS -o logs
#PBS -e logs
#PBS -m abe
#PBS -M Ming-Dao.Chia@anu.edu.au

## Modules

module load guppy/3.0.3

set -euo pipefail # safe mode
set -x # logging

## script variables

# call as follows:
# qsub -v fulldirname=/path/to/dir guppy_folder.pbs
dirname=$(basename "$fulldirname")

# prep folders
mkdir -p $PBS_JOBFS/fast5/
mkdir -p $PBS_JOBFS/fastq/

## copy reads to scratch disk
cp -r $fulldirname $PBS_JOBFS/fast5/

## basecall reads
guppy_basecaller -i $PBS_JOBFS/fast5/ -s $PBS_JOBFS/fastq/ --flowcell FLO-MIN106 --kit $kitname -r --num_callers ${PBS_NCPUS} --cpu_threads_per_caller 4

## bring the basecalls back
mkdir -p ${dirname}_basecalled
mv $PBS_JOBFS/fastq/* ${dirname}_basecalled/
