#!/bin/bash
#PBS -P xe2
#PBS -q normalsl
#PBS -l walltime=12:00:00
#PBS -l mem=32GB
#PBS -l jobfs=16GB
#PBS -l ncpus=16

## The job will be executed from current working directory instead of home.
#PBS -l wd

#PBS -o logs
#PBS -e logs
#PBS -m abe
#PBS -M Ming-Dao.Chia@anu.edu.au

## Modules
module load flye

set -euo pipefail # safe mode
set -x # logging

# use as
# qsub -v fullfilename=/path/to/fastq metaFlye.pbs
## script variables
filenameExt=$(basename "$fullfilename")
filename="${filenameExt%.*}"
dirPrefix=$(basename $(dirname "$fullfilename"))

## copy reads to scratch disk
cp $fullfilename $PBS_JOBFS/$filenameExt

## folder with assembly output
mkdir $PBS_JOBFS/${filename}_metaFlye

## do assembly
flye --nano-raw $PBS_JOBFS/$filenameExt --meta -o $PBS_JOBFS/${filename}_metaFlye -g 1G -t 16

## bring the demux back
mkdir -p ${filename}_metaFlye
mv $PBS_JOBFS/${filename}_metaFlye/* ${filename}_metaFlye/

