#!/bin/bash
#PBS -P xe2
#PBS -q normalsl
#PBS -l walltime=6:00:00
#PBS -l mem=32GB
#PBS -l jobfs=16GB
#PBS -l ncpus=16

## The job will be executed from current working directory instead of home.
#PBS -l wd
#PBS -o ra_logs
#PBS -e ra_logs
#PBS -m abe
#PBS -M Ming-Dao.Chia@anu.edu.au

## Modules
module load ra

set -euo pipefail # safe mode
set -x # logging

## script variables
filenameExt=$(basename "$fullfilename")
filename="${filenameExt%.*}"
dirPrefix=$(basename $(dirname "$fullfilename"))

ra $fullfilename -x ont -t 16 > ${filename}_ra.fasta

function fasta_stats { echo "Reads"; grep -c "^>" $1; echo "Bases"; grep -v ">" $1 | wc | awk '{print $3-$1}'; }
fasta_name=${filename}_ra.fasta
## send a slack message if it works
if [ -e $fasta_name ]
then
   msg="$fasta_name success! (unicycler hybrid)
"
   msg="${msg}$(fasta_stats $fasta_name)"
   qsub -v "message=${msg},slackcode=SUCCESS" /g/data/xe2/ming/pbs/send_slack.pbs
fi
