#!/bin/bash
#PBS -P xe2
#PBS -q normalsl
#PBS -l walltime=48:00:00
#PBS -l mem=96GB
#PBS -l jobfs=200GB
#PBS -l ncpus=16

## The job will be executed from current working directory instead of home.
#PBS -l wd
#PBS -o logs
#PBS -e logs
#PBS -m abe
#PBS -M Ming-Dao.Chia@anu.edu.au

## Modules
module load unicycler

set -euo pipefail # safe mode
set -x # logging

## script variables
longReadsExt=$(basename "$fullLR")
filename="${longReadsExt%.*}"
shortReadsExt=$(basename "$fullSR")

export TERM=xterm # bug fix

## run Unicycler
unicycler-runner.py -l $fullLR -s $fullSR -o $PBS_JOBFS/${filename}_unicycler_hybrid --mode bold -t $PBS_NCPUS

## bring the output back
mkdir -p ${filename}_unicycler_hybrid/
mv $PBS_JOBFS/${filename}_unicycler_hybrid/* ${filename}_unicycler_hybrid/

function fasta_stats { echo "Reads"; grep -c "^>" $1; echo "Bases"; grep -v ">" $1 | wc | awk '{print $3-$1}'; }
fasta_name=${filename}_unicycler_hybrid/assembly.fasta
## send a slack message if it works
if [ -e $fasta_name ]
then
   msg="$fasta_name success! (unicycler hybrid)
"
   msg="${msg}$(fasta_stats $fasta_name)"
   qsub -v "message=${msg},slackcode=SUCCESS" /g/data/xe2/ming/pbs/send_slack.pbs
fi
